/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CloneOperation,
  Error,
  GetApiV1TenantsTidClones200,
  GetApiV1TenantsTidClonesParams,
  PostApiV1TenantsTidClonesBody
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Clone requests are independent accepted work items outside the project/workspace operation model: Cloud accepts them in its own transaction, a Controller claims and dispatches them over the internal control contract, and only the submitting user can read them. requestId is the caller's durable request identity: repeating it with the same repository and branch returns the original request, a different input is 409 idempotency_conflict. repository must be an https or ssh URL the Controller can clone; branch is a short branch name, never HEAD. executionId and nodeId are null until a dispatch is recorded; a pending state means awaiting reconciliation, never failure. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/clones
 */
export const getApiV1TenantsTidClones = (
    tid: string,
    params?: GetApiV1TenantsTidClonesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidClones200>(
      {url: `/api/v1/tenants/${tid}/clones`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidClonesQueryKey = (tid: string,
    params?: GetApiV1TenantsTidClonesParams,) => {
    return [
    `/api/v1/tenants/${tid}/clones`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidClonesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidClonesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidClonesQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>> = ({ signal }) => getApiV1TenantsTidClones(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidClonesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>>
export type GetApiV1TenantsTidClonesQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidClones<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidClonesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidClones>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidClones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidClones<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidClonesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidClones>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidClones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidClones<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidClonesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/clones
 */

export function useGetApiV1TenantsTidClones<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidClonesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClones>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidClonesQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Clone requests are independent accepted work items outside the project/workspace operation model: Cloud accepts them in its own transaction, a Controller claims and dispatches them over the internal control contract, and only the submitting user can read them. requestId is the caller's durable request identity: repeating it with the same repository and branch returns the original request, a different input is 409 idempotency_conflict. repository must be an https or ssh URL the Controller can clone; branch is a short branch name, never HEAD. executionId and nodeId are null until a dispatch is recorded; a pending state means awaiting reconciliation, never failure. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/clones
 */
export const postApiV1TenantsTidClones = (
    tid: string,
    postApiV1TenantsTidClonesBody: PostApiV1TenantsTidClonesBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CloneOperation>(
      {url: `/api/v1/tenants/${tid}/clones`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidClonesBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidClonesMutationKey = () => ['postApiV1TenantsTidClones'] as const;

export const getPostApiV1TenantsTidClonesMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidClones>>, TError,PostApiV1TenantsTidClonesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidClones>>, TError,PostApiV1TenantsTidClonesMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidClonesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidClones>>, PostApiV1TenantsTidClonesMutationVariables> = (props) => {
          const {tid,data} = props ?? {};

          return  postApiV1TenantsTidClones(tid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidClonesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidClones>>>
    export type PostApiV1TenantsTidClonesMutationBody = PostApiV1TenantsTidClonesBody
    export type PostApiV1TenantsTidClonesMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidClonesMutationVariables = {tid: string;data: PostApiV1TenantsTidClonesBody}

    /**
 * @summary POST /api/v1/tenants/:tid/clones
 */
export const usePostApiV1TenantsTidClones = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidClones>>, TError,PostApiV1TenantsTidClonesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidClones>>,
        TError,
        PostApiV1TenantsTidClonesMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidClonesMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Clone requests are independent accepted work items outside the project/workspace operation model: Cloud accepts them in its own transaction, a Controller claims and dispatches them over the internal control contract, and only the submitting user can read them. requestId is the caller's durable request identity: repeating it with the same repository and branch returns the original request, a different input is 409 idempotency_conflict. repository must be an https or ssh URL the Controller can clone; branch is a short branch name, never HEAD. executionId and nodeId are null until a dispatch is recorded; a pending state means awaiting reconciliation, never failure. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/clones/:cloneId
 */
export const getApiV1TenantsTidClonesCloneId = (
    tid: string,
    cloneId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CloneOperation>(
      {url: `/api/v1/tenants/${tid}/clones/${cloneId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidClonesCloneIdQueryKey = (tid: string,
    cloneId: string,) => {
    return [
    `/api/v1/tenants/${tid}/clones/${cloneId}`
    ] as const;
    }


export const getGetApiV1TenantsTidClonesCloneIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError = ErrorType<Error>>(tid: string,
    cloneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidClonesCloneIdQueryKey(tid,cloneId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>> = ({ signal }) => getApiV1TenantsTidClonesCloneId(tid,cloneId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && cloneId !== null && cloneId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidClonesCloneIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>>
export type GetApiV1TenantsTidClonesCloneIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidClonesCloneId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError = ErrorType<Error>>(
 tid: string,
    cloneId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidClonesCloneId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError = ErrorType<Error>>(
 tid: string,
    cloneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidClonesCloneId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError = ErrorType<Error>>(
 tid: string,
    cloneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/clones/:cloneId
 */

export function useGetApiV1TenantsTidClonesCloneId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError = ErrorType<Error>>(
 tid: string,
    cloneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidClonesCloneId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidClonesCloneIdQueryOptions(tid,cloneId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






